### ISSUE TITLE
Preview image not included

### ISSUE THREAD

**Issue by daveloyall** [dzaima/BQN386#1]
I was able to preview your font using this web-based tool (maybe it is more like a browser-based tool).  http://torinak.com/font/lsfont.html

I thought about creating a pull request that includes "preview.html" which would be a script-less export of the runtime HTML/DOM content of that page after it has loaded your font.

But first.. Is that actually something you would like?

**Comment by dzaima** [comment]
This github repo mostly exists to host the sfd, the main place for the font being [paste](https://dzaima.github.io/paste#0DcZBTsJAGEDhfa@ChAso4SgchAWGZpz5O1OgQlpJaxUE24SlERdSk7Lsgju8E3AEZ/G9vGGvf0kvJyKF3mAFq9Gf6Ko9Th4wb5iP@yFmj3nHbJEdsmUv6AbjUEvUM2qNPePMABfhEmSOLJEFkqAFd0JWwbjLu6ytePzF5u1XV3QvATpDfihz0gjbEBs2T7gSyUi/iSW4Tpn@oV99R6gatUAld0RhcCvWlVffitXZa/zH3txLvcwTwoLDjENIWVHW/w#BQN) (speaking of which, it has changes that should be pushed here..); but I should really make this a more proper place for it; i'll take care of it

**Comment by dzaima** [comment]
Made a page - https://dzaima.github.io/BQN386/
