### ISSUE TITLE
Superscript numbers not aligned?

### ISSUE THREAD

**Issue by zoomlogo** [dzaima/BQN386#5]
![](https://user-images.githubusercontent.com/64531844/175928751-815cee6e-3f86-4e5c-88ec-f6c901565076.png)

**Comment by dzaima** [comment]
That's just APL385. 0 and 4-9 are in a different region in unicode, which'd explain why exactly they are weird.

**Comment by zoomlogo** [comment]
Other fonts have them look similar... 

Maybe I should open an issue @ APL386 repo.

**Comment by dzaima** [comment]
Fixed by ed800ac0302d5d62b80d7c65c4f3d5950dc2b08e
