### ISSUE TITLE
BQN386 not usable in gvim?

### ISSUE THREAD

**Issue by INIT-REF** [dzaima/BQN386#6]
I installed BQN386 under Ubuntu 22.04 and it is available system-wide in most applications. However, I can't select it in gvim. I first thought this was because it's not classified as monospaced, but according to fontforge it is.

Is there a way to make it available in gvim?

**Comment by dzaima** [comment]
Unfortunately, I do not know why this happens. I've tried to look into it (for gnome-terminal not gvim, but I'd assume the reason is the same) but search results nor looking at source code brought anything up.

**Comment by INIT-REF** [comment]
FYI it works fine in Mate's terminal, so for a vim terminal session it's ok.

**Comment by dzaima** [comment]
I think I got it working! (not tested with gvim, but it now appears in gnome-terminal)
